"""
Django settings for djangoproject project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 文件，保证后续 os.environ.get 能读到本地配置
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# 生产环境请务必通过 .env 或服务器环境变量传入真实值
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-before-production')

DEBUG = os.environ.get('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'logs',
    'targets',
    'monitor',
    'accounts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoproject.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'network_db',
        'USER': 'root',
        'PASSWORD': os.environ.get('DB_PASSWORD', '123456'),
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ====================== 时区与国际化配置（已正确修改） ======================
LANGUAGE_CODE = 'zh-hans'      # 中文界面
TIME_ZONE = 'Asia/Shanghai'    # 中国标准时间（解决时间差8小时的核心）
USE_I18N = True
USE_TZ = True                  # 推荐保持 True，让 Django 统一用 UTC 存储，显示时自动转换

# Static files
STATIC_URL = 'static/'

# ====================== 认证配置 ======================
LOGIN_URL = '/login/'                    # 未登录时跳转到登录页
LOGIN_REDIRECT_URL = '/'                 # 登录成功后默认跳转到仪表盘
LOGOUT_REDIRECT_URL = '/login/'          # 登出后跳转到登录页