# Generated by Django 6.0.4 on 2026-04-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='目标名称')),
                ('address', models.CharField(max_length=255, verbose_name='IP地址或域名')),
                ('target_type', models.CharField(choices=[('ip', 'IP地址'), ('domain', '域名'), ('url', 'URL')], default='domain', max_length=20, verbose_name='目标类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监控目标',
                'verbose_name_plural': '监控目标',
                'db_table': 'monitor_targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_time', models.FloatField(blank=True, null=True, verbose_name='延迟(ms)')),
                ('packet_loss', models.FloatField(blank=True, null=True, verbose_name='丢包率(%)')),
                ('http_response_time', models.FloatField(blank=True, null=True, verbose_name='HTTP响应时间(ms)')),
                ('dns_resolve_time', models.FloatField(blank=True, null=True, verbose_name='DNS解析时间(ms)')),
                ('network_jitter', models.FloatField(blank=True, null=True, verbose_name='网络抖动(ms)')),
                ('tcp_retransmit_rate', models.FloatField(blank=True, null=True, verbose_name='TCP重传率(%)')),
                ('status', models.CharField(default='unknown', max_length=20, verbose_name='状态')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitortarget', verbose_name='监控目标')),
            ],
            options={
                'verbose_name': '监控结果',
                'verbose_name_plural': '监控结果',
                'db_table': 'monitor_results',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('1m', '每分钟'), ('5m', '每5分钟'), ('15m', '每15分钟'), ('30m', '每30分钟'), ('1h', '每小时'), ('6h', '每6小时'), ('12h', '每12小时'), ('1d', '每天')], default='5m', max_length=10, verbose_name='监控频率')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitortarget', verbose_name='监控目标')),
            ],
            options={
                'verbose_name': '监控计划',
                'verbose_name_plural': '监控计划',
                'db_table': 'monitoring_schedules',
            },
        ),
    ]
