# Generated by Django 6.0.4 on 2026-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama (本地)'), ('custom', '自定义兼容接口')], default='openai', max_length=50)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('api_key', models.CharField(blank=True, help_text='留空则使用环境变量', max_length=255, null=True)),
                ('base_url', models.CharField(blank=True, help_text='自定义接口地址（如 Ollama: http://localhost:11434/v1）', max_length=255, null=True)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=400)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI 配置',
                'verbose_name_plural': 'AI 配置',
            },
        ),
    ]
