# Generated by Django 6.0.4 on 2026-04-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', '通义千问 (Qwen / DashScope)'), ('openai', 'OpenAI'), ('groq', 'Groq'), ('custom', '自定义 OpenAI 兼容接口')], default='deepseek', max_length=50, verbose_name='提供商')),
                ('model_name', models.CharField(default='deepseek-chat', max_length=100, verbose_name='模型名称')),
                ('api_key', models.CharField(blank=True, help_text='留空则自动从 .env 读取对应环境变量（推荐）', max_length=255, null=True, verbose_name='API Key')),
                ('base_url', models.CharField(blank=True, default='https://api.deepseek.com', max_length=255, null=True, verbose_name='Base URL')),
                ('temperature', models.FloatField(default=0.3, verbose_name='Temperature')),
                ('max_tokens', models.IntegerField(default=400, verbose_name='最大 Tokens')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'AI 配置',
                'verbose_name_plural': 'AI 配置',
            },
        ),
    ]
