# Generated by Django 6.0.4 on 2026-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_aiconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconfig',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='留空则尝试使用环境变量', max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='base_url',
            field=models.CharField(blank=True, help_text='例如 Ollama: http://localhost:11434/v1', max_length=255, null=True, verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='max_tokens',
            field=models.IntegerField(default=400, verbose_name='最大输出 Tokens'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='model_name',
            field=models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama (本地)'), ('custom', '自定义兼容接口')], default='openai', max_length=50, verbose_name='提供商'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='temperature',
            field=models.FloatField(default=0.3, verbose_name='Temperature'),
        ),
        migrations.AddConstraint(
            model_name='aiconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_config'),
        ),
    ]
