# Generated by Django 6.0.4 on 2026-04-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_aiconfig_created_at_alter_aiconfig_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiconfig',
            name='unique_active_config',
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='base_url',
            field=models.CharField(blank=True, default='https://api.deepseek.com', max_length=255, null=True, verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='max_tokens',
            field=models.IntegerField(default=400, verbose_name='最大 Tokens'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='model_name',
            field=models.CharField(default='deepseek-chat', max_length=100, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('groq', 'Groq'), ('custom', '自定义')], default='deepseek', max_length=50, verbose_name='提供商'),
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='api_key',
        ),
    ]
