# Generated by Django 6.0.4 on 2026-04-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_aiconfig_unique_active_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='留空则自动从 .env 读取对应环境变量（推荐）', max_length=255, null=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', '通义千问 (Qwen / DashScope)'), ('openai', 'OpenAI'), ('groq', 'Groq'), ('custom', '自定义 OpenAI 兼容接口')], default='deepseek', max_length=50, verbose_name='提供商'),
        ),
    ]
