# Generated by Django 6.0.4 on 2026-04-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_aiconfig_alter_monitorlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorlog',
            options={'ordering': ['-created_at'], 'verbose_name': '系统日志', 'verbose_name_plural': '系统日志'},
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='level',
            field=models.CharField(choices=[('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误')], default='INFO', max_length=10, verbose_name='日志级别'),
        ),
        migrations.AddField(
            model_name='monitorlog',
            name='log_type',
            field=models.CharField(choices=[('ping', 'Ping监控'), ('http', 'HTTP监控'), ('dns', 'DNS监控'), ('jitter', '抖动监控'), ('tcp_retrans', 'TCP重传'), ('system', '系统日志'), ('ai', 'AI分析')], default='system', max_length=20, verbose_name='日志类型'),
        ),
        migrations.AlterField(
            model_name='monitorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='monitorlog',
            name='result',
            field=models.TextField(verbose_name='日志内容'),
        ),
        migrations.AlterField(
            model_name='monitorlog',
            name='target',
            field=models.CharField(max_length=100, verbose_name='监控目标'),
        ),
    ]
