# Generated by Django 6.0.4 on 2026-04-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_monitorlog_options_monitorlog_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monitor', '监控数据分析'), ('logs', '系统日志分析')], default='monitor', max_length=20, verbose_name='报告类型')),
                ('title', models.CharField(default='网络诊断报告', max_length=200, verbose_name='报告标题')),
                ('content', models.TextField(verbose_name='报告内容')),
                ('model_used', models.CharField(max_length=100, verbose_name='使用的AI模型')),
                ('health_score', models.CharField(max_length=20, verbose_name='健康评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': 'AI分析报告',
                'verbose_name_plural': 'AI分析报告',
                'db_table': 'logs_aireport',
                'ordering': ['-created_at'],
            },
        ),
    ]
