# Generated by Django 6.0.4 on 2026-04-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_aireport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireport',
            name='health_score',
            field=models.CharField(help_text='优秀 / 良好 / 需关注 / 严重', max_length=20, verbose_name='健康评分'),
        ),
    ]
